[package]
name = "validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootspec = { version = "0.1.0", path = "../bootspec" }
serde_json = "1.0.83"
